### ISSUE TITLE
Add client support for Local hosted or Self hosted LLM model

### ISSUE THREAD

**Issue by SilinMeng0510** [huangyz0918/termax#38]
Lepton AI supports local deployment and cloud deployment on model from Huggingface

**Comment by sammcj** [comment]
Would be great to natively support Ollama.

**Comment by K0IN** [comment]
Can you provide me a example configuration for ollama? Also what model did you test with ollama?

**Comment by SilinMeng0510** [comment]
> Can you provide me a example configuration for ollama? Also what model did you test with ollama?

Hi K0IN, Here is an example Ollama configuration example. By default, Ollama uses "http://localhost:11434" in your local computer, so you can leave the host URL blank if you want default setting from Ollama. However, if you have other URL for Ollama, you can enter that during the configuration. For model, the default here is llama2. If you want other model supported by ollama, you can go to the website of Ollama and check it out: https://ollama.com/library.
<img width="524" alt="Screenshot 2024-04-24 at 2 49 08 PM" src="https://github.com/huangyz0918/termax/assets/89226819/89eb3c8b-6b45-48f6-b783-e81025822b89">

**Comment by K0IN** [comment]
Thank you so much for the quick reply, I missed that somehow 👍
